//Option 2a: fetch products on the client side in use effect
//from an internal api route

import Head from "next/head";
import Title from "@/components/Title";
import { useEffect, useState } from "react";

import { Product } from "./api/products";

function HomePage() {
  const [products, setProducts] = useState<Product[]>([]);

  useEffect(() => {
    (async () => {
      const response = await fetch("/api/products");

      const products = await response.json();

      setProducts(products);
    })();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4">
        <Title title="Next Shop" />
        <ul>
          {products.map((product) => (
            <li key={product.id}>{product.title}</li>
          ))}
        </ul>
      </main>
    </>
  );
}

export default HomePage;
